services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: major_data_link
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - major_data_link_pg:/var/lib/postgresql/data

volumes:
  major_data_link_pg:
